# Generated by Django 4.0.3 on 2022-03-23 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_order_orderitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='tracking_no',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
